### ISSUE TITLE
Age of War - Ticks for completable lines

### ISSUE THREAD

**Issue by baconheist** [Miniand/brdg.me-issues#53]
Show when a line is able to be completed on a current roll.

**Comment by beefsack** [comment]
Might use something other than a tick, planning to reduce the character set to just ASCII for all the games eventually.  Will have a play with it now.

**Comment by beefsack** [comment]
I ended up just adding bold and green to the line numbers which you can attack, not as good as ticks but hopefully good enough.  We can reopen this if it isn't quite good enough.
