### ISSUE TITLE
Splendor: missing maximum number of tokens rule

### ISSUE THREAD

**Issue by brewerns** [Miniand/brdg.me-issues#65]
A rule seems to be missing from the current splendour implementation:
'A player can never have more than 10 tokens at the end of
their turn (including jokers). If this happens, they must return
tokens until they only have 10 left.'

Have observed a filthy, cheating scumbag with an excess of tokens.

<img width="480" alt="screen shot 2015-08-13 at 11 22 40 am" src="https://cloud.githubusercontent.com/assets/13774181/9240766/a9879b4e-41ad-11e5-8bbe-a6503fe0c837.png">

**Comment by mickhrmweb** [comment]
@baconheist no more cheating for you.
